### ISSUE TITLE
[bug] /subscribe custom-channel refuses announcement channels

### ISSUE THREAD

**Issue by Venekiel** [Zechiax/Asterion#72]
Its auto-completion does not list announcement channels and does not seem to accept them when entered like <#channel_id>

Same with /change-channel new-channel

**Comment by Zechiax** [comment]
Thanks for letting me know, I was convinced it would show all suitable channels, but apparently not. 

I've made changes in #73 that should fix this, the only bad thing is it will currently show all available channels (and categories), I'll try to find a way to mitigate that but I'm yet to find a solution. That's why I'll keep #71 open for now.

The changes are live in the public instance, if you're using that.
